---
# Services to enable
_apache_services_enable:
  all: []
  CentOS_7:
    - httpd
  RedHat_7:
    - httpd
  CentOS_8:
    - httpd
  RedHat_8:
    - httpd
  Fedora_31:
    - httpd
  Debian_10:
    - apache2
  Ubuntu_18:
    - apache2
