---
# Template configuration files for apache

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ apache_templates_copy }}"
  when: apache_copy_templates
